%
%  revised  front.tex  2017-01-08  Mark Senn  http://engineering.purdue.edu/~mark
%  created  front.tex  2003-06-02  Mark Senn  http://engineering.purdue.edu/~mark
%
%  This is ``front matter'' for the thesis.
%
%  Regarding ``References'' below:
%      KEY    MEANING
%      PU     ``A Manual for the Preparation of Graduate Theses'',
%             The Graduate School, Purdue University, 1996.
%      PU8    ``A Manual for the Preparation of Graduate Theses'',
%             Eighth Revise Edition, Purdue University.
%      TCMOS  The Chicago Manual of Style, Edition 14.
%      WNNCD  Webster's Ninth New Collegiate Dictionary.
%
%  Lines marked with "%%" may need to be changed.
%

  % Statement of Thesis/Dissertation Approval Page
  % This page is REQUIRED.  The page should be numbered page ``ii''
  % and should NOT be listed in your TABLE OF CONTENTS.
  % References: PU8 ordinal pages 5 and 29.
  % The web page https://engineering.purdue.edu/AAE retrieved on
  % January 8, 2017 had "School of Aeronautics and Astronautics"---that
  % is used instead of "Department af Aeronautics and Astronautics"
  % below.

  % retrieved 9/11/17 from http://www.stat.purdue.edu/people/faculty/
  % used title in personal section
\begin{statement}
  \entry{Dr.~William Cleveland, Co-Chair}{Shanti S. Gupta Distinguished Professor of Statistics}
  \entry{Dr.~Ryan Hafen, Co-Chair}{Adjunct Assistant Professor of Statistics}
  \entry{Dr.~Bowei Xi}{Associate Professor of Statistics}
  \entry{Dr.~Vinayak Rao}{Assistant Professor of Statistics}
  \approvedby{Dr.~Hao Zhang}{Department Head of Statistics}
\end{statement}

  % Dedication page is optional.
  % A name and often a message in tribute to a person or cause.
  % References: PU 15, WNNCD 332.
% \begin{dedication}
%   This is the dedication.
% \end{dedication}

  % Acknowledgements page is optional but most theses include
  % a brief statement of apreciation or recognition of special
  % assistance.
  % Reference: PU 16.
\begin{acknowledgments}
  On the academic front, I would like to thank my co-chair advisors, Ryan Hafen and Bill Cleveland.  I am grateful for their consistent guidance and willingness to take risks on new ideas.  I would like to thank my long-time academic advisors: Di Cook and Hadley Wickham.  Without their encouragement and support over the past decade, I would not be where I am today.  \emph{If I have seen further, it is only by standing on the shoulders of giants.}

  I am grateful to Purdue Statistics for providing an excellent environment for both learning and research.  Thank you Rebecca Doerge and Mark Ward for helping steer my early stages at Purdue and always lending me an ear.  Thank you Doug Crabill for his willingness to share his deep technical knowledge at any moment.  I am honored to have been able to attend numerous Wednesday Night Probability Seminars.

  To my parents, I can not thank you enough for your unconditional love and support.  Whether it is your well timed advice or your nodding and smiles as I ramble about a topic, I can not tell you how much I appreciate it.

  And to Tracy, from traveling all across the globe to spending late nights in the library, I am truly thankful for having you in my life.  Your never ending patience, encouragement, and love always makes me smile.
\end{acknowledgments}

  % The preface is optional.
  % References: PU 16, TCMOS 1.49, WNNCD 927.
% \begin{preface}
%   This is the preface.
% \end{preface}

  % The Table of Contents is required.
  % The Table of Contents will be automatically created for you
  % using information you supply in
  %     \chapter
  %     \section
  %     \subsection
  %     \subsubsection
  % commands.
  % Reference: PU 16.
\tableofcontents

  % If your thesis has tables, a list of tables is required.
  % The List of Tables will be automatically created for you using
  % information you supply in
  %     \begin{table} ... \end{table}
  % environments.
  % Reference: PU 16.
%\listoftables

  % If your thesis has figures, a list of figures is required.
  % The List of Figures will be automatically created for you using
  % information you supply in
  %     \begin{figure} ... \end{figure}
  % environments.
  % Reference: PU 16.
\listoffigures

  % List of Symbols is optional.
  % Reference: PU 17.
% \begin{symbols}
%   $m$& mass\cr
%   $v$& velocity\cr
% \end{symbols}

  % List of Abbreviations is optional.
  % Reference: PU 17.
\begin{abbreviations}
  API & Application Protocol Interface\cr
  CCA & Canonical Correlation Analysis \cr
  HTTP & Hypertext Transfer Protocol \cr
  PDF & Portable Document Format \cr
  REST & Representational State Transfer \cr
  RESTful & API that has REST qualities \cr
  URL & Uniform Resource Locator\cr
  % bcf& billion cubic feet\cr
  % BMOC& big man on campus\cr
\end{abbreviations}

  % Nomenclature is optional.
  % Reference: PU 17.
% \begin{nomenclature}
%   Alanine& 2-Aminopropanoic acid\cr
%   Valine& 2-Amino-3-methylbutanoic acid\cr
% \end{nomenclature}

  % Glossary is optional
  % Reference: PU 17.
\begin{glossary}
  % chick& female, usually young\cr
  % dude& male, usually young\cr
  Axes & All axis areas of a plot. Typically only X and Y. \cr
  Browser & Computer application that visits websites using the internet \cr
  Directed Graph & A graph whose edges have a defined start and end\cr
  Host & a web server with a unique URL \cr
  Interface & A point where two systems, subjects, organizations, etc., meet and interact \cr
  Jittered & Points slightly altered from their original position to help overcome overplotting \cr
  Overplotted & What occurs too many points are displayed to see the underlying structure \cr
  Panel & Plotting area.  This is not limited to the strips, axes, and plot content. When used in the context of a plot matrix, it refers to a single sub plot within the plot matrix.\cr
  Plot & A statistical graphic displaying the relationship between variables.\cr
  Plot content & Plot area within the axes. \cr
  Server & A machine that calculates, stores, retrieves, and communicates information \cr
  Strip & A panel label \cr
  Web Server & A server that returns websites or data related to a website \cr
  URL, web address & Uniform Resource Locator. Also the address of a World Wide Web page \cr
\end{glossary}

% Abstract is required.
% Note that the information for the first paragraph of the output
% doesn't need to be input here...it is put in automatically from
% information you supplied earlier using \title, \author, \degree,
% and \majorprof.
% Reference: PU 17.
\begin{abstract}
  % problem is important?
  % what have people done?
  %   2-3 sentences
  % what is missing?
  %   However, ...
  % we address this missing by...?
  % In this work, we fill this gap by BLAH using packages A, B, C.
  %
  % 3x more sentences describing each package
  %   ggduo does a gen pairs plot
  %   autocogs does X and addresses Y
  %   gqlr does A and bridges the gap of B
  %
  % stress the importance of the contribution
  %   These three packages will address issues....

  % problem is important?
  Statistical visualization of large-scale data has become an increasingly essential task in the era of \emph{big data}.
  In particular, exploratory data analysis and visualization is the first step towards any in-depth statistical modeling and analysis.
  Being able to rapidly specify and generate visualizations regardless of data-scale is crucial.
  % what have people done?
  %   2-3 sentences
  Trelliscope handles data visualization at scale by attaching cognostics (univariate metrics) to each panel aiding in the organization of panels of interest.
  % what is missing?
  %   However, ...
  While Trelliscope provides a general framework for visualizing data at scale, there are several aspects that can be improved to help users generate displays more rapidly (such as cognostics, axis scales, etc.).
  When visually modeling complex data with Trelliscope, traditional two-grouped plot matrices do not allow for a mixed-scale axis to display both continuous and discrete data natively.
  Web-based visualization systems like Trelliscope, that retrieve information from a back-end service such as R, must maximize performance for an engaging user experience.
  % we address this missing by...?
  %   In this work, we fill this gap by BLAH using packages A, B, C.
  % 3x more sentences describing each package
  %   ggduo does a gen pairs plot
  %   autocogs does X and addresses Y
  %   gqlr does A and bridges the gap of B
  Addressing the mixed-scale plot matrix axis, a generalized plot matrix is developed for two-grouped data which displays both continuous and discrete data using appropriate visualization methods for each panel.
  To compliment Trelliscope's panel organization, automatic cognostic summaries are established by mapping the context of what is visualized to classes of metrics that are meaningful for each type of visualization layer at no additional user effort.
  Finally, communication from web-based visualization systems to back-end R services is greatly improved by leveraging the GraphQL query language which minimizes the number of required data queries needed to perform data extraction.
  % stress the importance of the contribution
  %   These three packages will address issues....
  Together, these three contributions curtail the increasing complexity and scale of data visualization.
\end{abstract}
